version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  #logstash:
    #image: docker.elastic.co/logstash/logstash:7.15.2
    #container_name: logstash
    #volumes:
      #- ./logstash-config:/usr/share/logstash/pipeline
    #ports:
      #- "5000:5000"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
